### ISSUE TITLE
Milestone: Set up your Kanban board

### ISSUE THREAD

**Issue by Arslan49sp** [Arslan49sp/desi-dhaba-js-capstone#21]
[Link of the project](https://github.com/Arslan49sp/desi-dhaba-js-capstone/projects/1)
[Link of my repository](https://github.com/Arslan49sp/desi-dhaba-js-capstone)

I am doing this project solo.

**Comment by Arslan49sp** [comment]
Ye i attach the screenshot.

**Comment by Arslan49sp** [comment]
Kindly approve this as soon as possible because I have to move on .

**Comment by Arslan49sp** [comment]
![image](https://github.com/Arslan49sp/desi-dhaba-js-capstone/assets/49227101/707a3c6c-fffb-4da6-86b9-8dee3af8c40b)
 this is the screenshot of that email

**Comment by binhussen** [comment]
Hi @Arslan49sp , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
![ChopApproveCopApproveGIF](https://github.com/Arslan49sp/desi-dhaba-js-capstone/assets/52010789/ecf72622-ee71-4b7d-9a22-e744ae3bd16f)

## Highlights
- Used Given Canban Template ✔️
- Assigned All Issues ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
